[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Steven Franke", email = "steven.franke@awi.de"}]
dynamic = ["version", "description"]
