def get_CReSIS_radar_profile_metadata():

    import numpy as np

    ###################
    # All CReSIS RDS

    dict_CReSIS_rds = {"Campaign Folder" : ["1993_Greenland_P3_standard",
                                            "1995_Greenland_P3_standard",
                                            "1996_Greenland_P3_standard",
                                            "1997_Greenland_P3_standard",
                                            "1998_Greenland_P3_standard",
                                            "1999_Greenland_P3_standard",
                                            "2001_Greenland_P3_standard",
                                            "2002_Antarctica_P3chile_standard",
                                            "2002_Greenland_P3_standard",
                                            "2003_Greenland_P3_standard",
                                            "2004_Antarctica_P3chile_standard",
                                            "2005_Greenland_TO_standard",
                                            "2006_Greenland_TO_standard",
                                            "2007_Greenland_P3_standard",
                                            "2008_Greenland_TO_standard",
                                            "2009_Antarctica_DC8_standard",
                                            "2009_Antarctica_TO_Gambit_standard",
                                            "2009_Antarctica_TO_standard",
                                            "2009_Greenland_TO_standard",
                                            "2010_Antarctica_DC8_standard",
                                            "2010_Greenland_DC8_standard",
                                            "2010_Greenland_P3_standard",
                                            "2011_Antarctica_DC8_standard",
                                            "2011_Antarctica_TO_standard",
                                            "2012_Antarctica_DC8_standard",
                                            "2012_Greenland_P3_standard",
                                            "2013_Antarctica_Basler_standard",
                                            "2013_Antarctica_P3_standard",
                                            "2013_Greenland_P3_standard",
                                            "2014_Antarctica_DC8_standard",
                                            "2014_Greenland_P3_standard",
                                            "2015_Greenland_C130_standard",
                                            "2016_Antarctica_DC8_standard",
                                            "2016_Greenland_G1XB_standard",
                                            "2016_Greenland_P3_standard",
                                            "2016_Greenland_Polar6_standard",
                                            "2016_Greenland_TOdtu_standard",
                                            "2017_Antarctica_Basler_standard",
                                            "2017_Antarctica_P3_standard",
                                            "2017_Greenland_P3_standard",
                                            "2018_Antarctica_DC8_standard",
                                            "2018_Greenland_P3_standard",
                                            "2019_Antarctica_GV_standard",
                                            "2019_Greenland_P3_standard",
                                            "2022_Antarctica_BaslerMKB_standard",
                                            "2023_Antarctica_BaslerMKB_standard"],

                    "Season Name"       :  ["ARK 1993",
                                            "ARK 1995",
                                            "ARK 1996",
                                            "ARK 1997",
                                            "ARK 1998",
                                            "ARK 1999",
                                            "ARK 2001",
                                            "ANT 2002/03",
                                            "ARK 2002",
                                            "ARK 2003",
                                            "ANT 2004/05",
                                            "ARK 2005",
                                            "ARK 2006",
                                            "ARK 2007",
                                            "ARK 2008",
                                            "ANT 2009/10",
                                            "ANT 2008/09",
                                            "ANT 2009/10",
                                            "ARK 2009",
                                            "ANT 2010/11",
                                            "ARK 2010",
                                            "ARK 2010",
                                            "ANT 2011/10",
                                            "ANT 2011/10",
                                            "ANT 2011/12",
                                            "ARK 2012",
                                            "ANT 2013/14",
                                            "ANT 2013/14",
                                            "ARK 2013",
                                            "ANT 2013/14",
                                            "ARK 2014",
                                            "ARK 2015",
                                            "ANT 2015/16",
                                            "ARK 2016",
                                            "ARK 2016",
                                            "ARK 2016",
                                            "ARK 2016",
                                            "ANT 2017/18",
                                            "ANT 2017/18",
                                            "ARK 2017",
                                            "ANT 2018/19",
                                            "ARK 2018",
                                            "ANT 2019/20",
                                            "ARK 2019",
                                            "ANT 2022/23",
                                            "ANT 2023/24"],

                    "Radar System"     :   ["ICORDS",
                                            "ICORDS",
                                            "ICORDS",
                                            "ICORDS",
                                            "ICORDS 2",
                                            "ICORDS 2",
                                            "ICORDS 2",
                                            "ICORDS 2",
                                            "ICORDS 2",
                                            "ACORDS",
                                            "ACORDS",
                                            "ACORDS",
                                            "MCRDS",
                                            "MCRDS",
                                            "MCRDS",
                                            "MCoRDS",
                                            "MCoRDS",
                                            "MCoRDS",
                                            "MCoRDS",
                                            "MCoRDS",
                                            "MCoRDS",
                                            "MCoRDS",
                                            "MCoRDS",
                                            "MCoRDS 2",
                                            "MCoRDS 2",
                                            "MCoRDS 2",
                                            "MCoRDS 4",
                                            "MCoRDS 2",
                                            "MCoRDS 3",
                                            "MCoRDS 3",
                                            "MCoRDS 2",
                                            "MCoRDS 5",
                                            "MCoRDS 3",
                                            "MCoRDS 5",
                                            "MCoRDS 5",
                                            "MCoRDS 5",
                                            "MCoRDS 3",
                                            "MCoRDS 5",
                                            "MCoRDS 3",
                                            "MCoRDS 3",
                                            "MCoRDS 3",
                                            "MCoRDS 3",
                                            "MCoRDS 3",
                                            "MCoRDS 3",
                                            "MARFA",
                                            "MARFA"],

                    "Radar Specs"        : ["141.5-158.5 MHz",
                                            "141.5-158.5 MHz",
                                            "141.5-158.5 MHz",
                                            "141.5-158.5 MHz",
                                            "141.5-158.5 MHz",
                                            "141.5-158.5 MHz",
                                            "141.5-158.5 MHz",
                                            "141.5-158.5 MHz",
                                            "141.5-158.5 MHz",
                                            "140-160 MHz",
                                            "140-160 MHz",
                                            "140-160 MHz",
                                            "140-160 MHz",
                                            "140-160 MHz",
                                            "140-160 MHz",
                                            "189.15-198.65 MHz",
                                            "140-160 MHz",
                                            "140-160 MHz",
                                            "140-160 MHz",
                                            "180-210 MHz",
                                            "140-160 MHz",
                                            "140-160 MHz",
                                            "180-210 MHz",
                                            "180-210 MHz",
                                            "180-210 MHz",
                                            "180-210 MHz",
                                            "180-210 MHz",
                                            "180-210 MHz",
                                            "180-210 MHz",
                                            "165-215 MHz",
                                            "180-210 MHz",
                                            "180-230 MHz",
                                            "180-210 MHz",
                                            "180-210 MHz",
                                            "150-450 MHz",
                                            "150-520 MHz",
                                            "180-210 MHz",
                                            "150-450 MHz",
                                            "150-450 MHz",
                                            "180-210 MHz",
                                            "180-210 MHz",
                                            "180-210 MHz",
                                            "236-254 MHz",
                                            "180-210 MHz",
                                            "52.5-67.5 MHz",
                                            "52.5-67.5 MHz"],

                    "Platform"          :  ["Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Twin Otter",
                                            "Twin Otter",
                                            "Lockheed P-3",
                                            "Twin Otter",
                                            "Douglas DC-8",
                                            "Twin Otter",
                                            "Twin Otter",
                                            "Twin Otter",
                                            "Douglas DC-8",
                                            "Douglas DC-8",
                                            "Lockheed P-3",
                                            "Douglas DC-8",
                                            "Twin Otter",
                                            "Douglas DC-8",
                                            "Lockheed P-3",
                                            "Basler BT-67",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Douglas DC-8",
                                            "Lockheed P-3",
                                            "Lockheed C-130",
                                            "Douglas DC-8",
                                            "G1XB",
                                            "Lockheed P-3",
                                            "Polar 6",
                                            "Twin Otter (DTU)",
                                            "Basler BT-67",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Douglas DC-8",
                                            "Lockheed P-3",
                                            "Gulfstream V",
                                            "Lockheed P-3",
                                            "Basler BT-67",
                                            "Basler BT-67"],
                                        
                    "Campaign Name"     :  ["1993_Greenland_P3_standard",
                                            "1995_Greenland_P3_standard",
                                            "1996_Greenland_P3_standard",
                                            "1997_Greenland_P3_standard",
                                            "1998_Greenland_P3_standard",
                                            "1999_Greenland_P3_standard",
                                            "2001_Greenland_P3_standard",
                                            "2002_Antarctica_P3chile_standard",
                                            "2002_Greenland_P3_standard",
                                            "2003_Greenland_P3_standard",
                                            "2004_Antarctica_P3chile_standard",
                                            "2005_Greenland_TO_standard",
                                            "2006_Greenland_TO_standard",
                                            "2007_Greenland_P3_standard",
                                            "2008_Greenland_TO_standard",
                                            "2009_Antarctica_DC8_standard",
                                            "2009_Antarctica_TO_Gambit_standard",
                                            "2009_Antarctica_TO_standard",
                                            "2009_Greenland_TO_standard",
                                            "2010_Antarctica_DC8_standard",
                                            "2010_Greenland_DC8_standard",
                                            "2010_Greenland_P3_standard",
                                            "2011_Antarctica_DC8_standard",
                                            "2011_Antarctica_TO_standard",
                                            "2012_Antarctica_DC8_standard",
                                            "2012_Greenland_P3_standard",
                                            "2013_Antarctica_Basler_standard",
                                            "2013_Antarctica_P3_standard",
                                            "2013_Greenland_P3_standard",
                                            "2014_Antarctica_DC8_standard",
                                            "2014_Greenland_P3_standard",
                                            "2015_Greenland_C130_standard",
                                            "2016_Antarctica_DC8_standard",
                                            "2016_Greenland_G1XB_standard",
                                            "2016_Greenland_P3_standard",
                                            "2016_Greenland_Polar6_standard",
                                            "2016_Greenland_TOdtu_standard",
                                            "2017_Antarctica_Basler_standard",
                                            "2017_Antarctica_P3_standard",
                                            "2017_Greenland_P3_standard",
                                            "2018_Antarctica_DC8_standard",
                                            "2018_Greenland_P3_standard",
                                            "2019_Antarctica_GV_standard",
                                            "2019_Greenland_P3_standard",
                                            "2022_Antarctica_BaslerMKB_standard",
                                            "2023_Antarctica_BaslerMKB_standard"],

                    "Campaign Name Long":  ["1993_Greenland_P3_standard",
                                            "1995_Greenland_P3_standard",
                                            "1996_Greenland_P3_standard",
                                            "1997_Greenland_P3_standard",
                                            "1998_Greenland_P3_standard",
                                            "1999_Greenland_P3_standard",
                                            "2001_Greenland_P3_standard",
                                            "2002_Antarctica_P3chile_standard",
                                            "2002_Greenland_P3_standard",
                                            "2003_Greenland_P3_standard",
                                            "2004_Antarctica_P3chile_standard",
                                            "2005_Greenland_TO_standard",
                                            "2006_Greenland_TO_standard",
                                            "2007_Greenland_P3_standard",
                                            "2008_Greenland_TO_standard",
                                            "2009_Antarctica_DC8_standard",
                                            "2009_Antarctica_TO_Gambit_standard",
                                            "2009_Antarctica_TO_standard",
                                            "2009_Greenland_TO_standard",
                                            "2010_Antarctica_DC8_standard",
                                            "2010_Greenland_DC8_standard",
                                            "2010_Greenland_P3_standard",
                                            "2011_Antarctica_DC8_standard",
                                            "2011_Antarctica_TO_standard",
                                            "2012_Antarctica_DC8_standard",
                                            "2012_Greenland_P3_standard",
                                            "2013_Antarctica_Basler_standard",
                                            "2013_Antarctica_P3_standard",
                                            "2013_Greenland_P3_standard",
                                            "2014_Antarctica_DC8_standard",
                                            "2014_Greenland_P3_standard",
                                            "2015_Greenland_C130_standard",
                                            "2016_Antarctica_DC8_standard",
                                            "2016_Greenland_G1XB_standard",
                                            "2016_Greenland_P3_standard",
                                            "2016_Greenland_Polar6_standard",
                                            "2016_Greenland_TOdtu_standard",
                                            "2017_Antarctica_Basler_standard",
                                            "2017_Antarctica_P3_standard",
                                            "2017_Greenland_P3_standard",
                                            "2018_Antarctica_DC8_standard",
                                            "2018_Greenland_P3_standard",
                                            "2019_Antarctica_GV_standard",
                                            "2019_Greenland_P3_standard",
                                            "2022_Antarctica_BaslerMKB_standard",
                                            "2023_Antarctica_BaslerMKB_standard"],

                    "Campaign PI"       : np.repeat("None", 46),
                    "Grant ID"          : np.repeat("None", 46),
                    "Pangaea Identifyer" : np.repeat("None", 46),
                    "Radar Data DOI"     : np.repeat("None", 46)}

    ## ================================================================================================= ##
    ## ================================================================================================= ##


    ########################################
    # All CReSIS Accumulation Radar Seasons

    dict_CReSIS_accum = {"Campaign Folder" : ["2010_Greenland_P3_qlook",
                                            "2011_Greenland_P3_qlook",
                                            "2012_Greenland_P3_qlook",
                                            "2013_Antarctica_P3_qlook",
                                            "2013_Greenland_P3_qlook",
                                            "2014_Greenland_P3_qlook",
                                            "2017_Greenland_P3_standard",
                                            "2018_Greenland_P3_qlook",
                                            "2023_Antarctica_BaslerMKB_standard"],

                    "Season Name"       :  ["ARK 2010",
                                            "ARK 2011",
                                            "ARK 2012",
                                            "ANT 2013/14",
                                            "ARK 2013",
                                            "ARK 2014",
                                            "ARK 2017",
                                            "ARK 2018",
                                            "ANT 2023/24"],

                    "Radar System"     :   ["CReSIS Accumulation Radar",
                                            "CReSIS Accumulation Radar",
                                            "CReSIS Accumulation Radar",
                                            "CReSIS Accumulation Radar",
                                            "CReSIS Accumulation Radar",
                                            "CReSIS Accumulation Radar",
                                            "CReSIS Accumulation Radar",
                                            "CReSIS Accumulation Radar",
                                            "CReSIS Accumulation Radar"],

                    "Radar Specs"        : ["550-900 MHz",
                                            "550-900 MHz",
                                            "600-900 MHz",
                                            "600-900 MHz",
                                            "600-900 MHz",
                                            "600-900 MHz",
                                            "600-900 MHz",
                                            "600-900 MHz",
                                            "600-900 MHz"],

                    "Platform"          :  ["Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Lockheed P-3",
                                            "Basler BT-67"],
                                        
                    "Campaign Name"     :  ["2010_Greenland_P3_qlook",
                                            "2011_Greenland_P3_qlook",
                                            "2012_Greenland_P3_qlook",
                                            "2013_Antarctica_P3_qlook",
                                            "2013_Greenland_P3_qlook",
                                            "2014_Greenland_P3_qlook",
                                            "2017_Greenland_P3_standard",
                                            "2018_Greenland_P3_qlook",
                                            "2023_Antarctica_BaslerMKB_standard"],

                    "Campaign Name Long":  ["2010_Greenland_P3_qlook",
                                            "2011_Greenland_P3_qlook",
                                            "2012_Greenland_P3_qlook",
                                            "2013_Antarctica_P3_qlook",
                                            "2013_Greenland_P3_qlook",
                                            "2014_Greenland_P3_qlook",
                                            "2017_Greenland_P3_standard",
                                            "2018_Greenland_P3_qlook",
                                            "2023_Antarctica_BaslerMKB_standard"],

                    "Campaign PI"       :  ["Carl Leuschen (CReSIS)",
                                            "Carl Leuschen (CReSIS)",
                                            "None",
                                            "None",
                                            "None",
                                            "None",
                                            "None",
                                            "None",
                                            "None"],
                                            
                    "Grant ID"          : np.repeat("None", 9),
                    "Pangaea Identifyer" : np.repeat("None", 9),
                    "Radar Data DOI"     : np.repeat("None", 9)}
    
    
    return dict_CReSIS_rds, dict_CReSIS_accum